#Application browser
browser=chrome

# Application URL
url=https://www.demoblaze.com/

#User credentials

username=Vikramraja
password=Vikramraja@12345#

screenshotPath=.//screenshots//

name=Vikram
country=India
city=Chennai
card=123456789
month=08
year=2026